FROM mcr.microsoft.com/dotnet/core/runtime:3.1

# Set the working directory
WORKDIR /app

# Copy the app
COPY bin/Release/publish /app

ENV TZ=Europe/Brussels
ENV CONNECTION_STRING=...

# Start the app
ENTRYPOINT["dotnet", "MijnSauna.Middleware.Processor"]