trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/MijnSauna.Frontend.Maui/*
    - src/MijnSauna.Common.Client/*
    - src/MijnSauna.Common.DataTransferObjects/*

pool:
  vmImage: 'windows-2022'

steps:

- task: CmdLine@2
  displayName: 'Install MAUI workload for dotnet CLI'
  inputs:
    script: 'dotnet workload install maui'

- task: DotNetCoreCLI@2
  displayName: 'Publish MijnSauna.Frontend.Maui.csproj for net7.0-android'
  inputs:
    command: 'publish'
    projects: 'src\MijnSauna.Frontend.Maui\MijnSauna.Frontend.Maui.csproj'
    arguments: '-c Release -f net7.0-android'

- task: CopyFiles@2
  displayName: 'Copy signed packages to ArtifactStagingDirectory'
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: |
      **/*-Signed.aab
      **/*-Signed.apk
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish signed packages to ArtifactStagingDirectory'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: MijnSauna.Frontend.Maui