# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - src/MijnSauna.Backend.Api/*
    - src/MijnSauna.Backend.Logic/*
    - src/MijnSauna.Backend.Sensors/*
    - src/MijnSauna.Backend.Mappers/*
    - src/MijnSauna.Backend.DataAccess/*
    - src/MijnSauna.Backend.Model/*
    - src/MijnSauna.Backend.Common/*
    - src/MijnSauna.Backend.Tests/*
    - src/MijnSauna.Common.Client/*
    - src/MijnSauna.Common.DataTransferObjects/*
    - src/MijnSauna.Common.Protobuf/*

pool:
  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/backend/**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Use .NET SDK (5.0)'
  inputs:
    packageType: sdk
    version: 5.0.203
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages
  inputs:
    command: 'restore'
    projects: | 
      **/src/MijnSauna.Common.*/*.csproj
      **/src/MijnSauna.Backend.*/*.csproj

- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: 'build'
    projects: | 
      **/src/MijnSauna.Common.*/*.csproj
      **/src/MijnSauna.Backend.*/*.csproj

- task: DotNetCoreCLI@2
  displayName: Run UnitTests
  inputs:
    command: 'test'
    projects: | 
      **/src/MijnSauna.Common.*/*.csproj
      **/src/MijnSauna.Backend.*/*.csproj
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude=[System.*]*%2c[xunit.*]*'

- script: |
    dotnet tool install dotnet-reportgenerator-globaltool --tool-path . --version 4.3.9
    ./reportgenerator "-reports:$(Build.SourcesDirectory)/src/MijnSauna.Backend.Tests/coverage.cobertura.xml" "-targetdir:$(Build.SourcesDirectory)/src/MijnSauna.Backend.Tests/results" "-reporttypes:HTMLInline;HTMLChart"
- task: PublishTestResults@2
  displayName: Publish test results
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage results
  inputs:
    summaryFileLocation: $(Build.SourcesDirectory)/src/MijnSauna.Backend.Tests/coverage.cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)/src/MijnSauna.Backend.Tests/results
    codecoverageTool: cobertura

- script: |
    dotnet publish ./src/MijnSauna.Backend.Api --configuration "Release" --output ./src/MijnSauna.Backend.Api/bin/Release/publish

- script: |
    cd ./src/MijnSauna.Backend.Api
    docker build -t djohnnie/mijnsauna-api .
    docker login -u $(dockerId) -p $(dockerPwd)
    docker push djohnnie/mijnsauna-api
