trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - src/MijnSauna.Frontend.Phone/*
    - src/MijnSauna.Frontend.Phone.Android/*
    - src/MijnSauna.Common.Client/*
    - src/MijnSauna.Common.DataTransferObjects/*
    - src/MijnSauna.Common.Protobuf/*

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/MijnSauna.Frontend.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/MijnSauna.Frontend.Phone.Android.csproj'
    configuration: Release

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/src/MijnSauna.Frontend.Phone/MijnSauna.Frontend.Phone.Android/bin/Release'
    contents: '*.apk'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'MyApp'